#!/bin/bash
#global vars to use in the other functionsi
ipAddress=10.2.7.244
emailAddress=cit470.fa2018.team.5@gmail.com
groupName="cit470 Group 5"
logFile=apache-install.log
#this installs apache
function apacheInstall(){
        echo "Installing OpenSSL, GCC, and Apache" | tee -a $logFile
        yum install -y mod_ssl openssl gcc
        wget https://archive.apache.org/dist/httpd/httpd-2.2.0.tar.gz >> $logFile
        tar xvf httpd-2.2.0.tar.gz >> log_file
        cd httpd-2.2.0
        ./configure --prefix=/usr/local/apache --enable-so
        make
        make install
        echo -e "OK\n" | tee -a $logFile
}
#this updates the firewall to accept ports 80 and 443
function firewallConf {
        echo "updating firewall rules" | tee -a $logFile
        iptables -I INPUT -p tcp --dport 80 -j ACCEPT
        iptables -I INPUT -p tcp --dport 443 -j ACCEPT
        iptables-save >> /etc/sysconfig/iptables
        echo -e "OK\n" | tee -a $logFile
}
#generats private key and the self-signed cert
function certCreate {
        echo "generation private key and the self-signed cert" | tee -a $logFile
        openssl genrsa -out /etc/pki/tls/private/apacheprivatekey.key
        openssl req -new -key /etc/pki/tls/private/apacheprivatekey.key -out /etc/pki/tls/private/apachecsr.csr -subj "/C=US/ST=Kentucky/L=Highland Heights/O=Northern Kentucky University/OU=\$groupName/CN=\$HOSTNAME/emailAddress=\$emailAddress"
        openssl x509 -req -days 365 -in /etc/pki/tls/private/apachecsr.csr -signkey /etc/pki/tls/private/apacheprivatekey.key -out /etc/pki/tls/certs/apachecertificate.crt
        echo -e "OK\n" | tee -a $logFile
}
#configs apache
function apachConf {
        echo "Config Apache" | tee -a $logFile
        sed -i "s/#ServerName www.example.com:80/ServerName $ipAddress:80/" /etc/httpd/conf/httpd.conf
        sed -i "s/ServerAdmin root@localhost/ServerAdmin $emailAddress/" /etc/httpd/conf/httpd.conf
        echo -e "\n### Global Rewrite Rules\n" >> /etc/httpd/conf/httpd.conf
	sed -i "RewriteEngine On" /etc/httpd/conf/httpd.conf
        sed -i "RewriteRule ^/users/(.*)$ https://%{SERVER_NAME}/~\$1 [R]" /etc/httpd/conf/httpd.conf
        #This enables the userDir module and configures apache for user hosted sites
        sed -i "s/UserDir disable/#UserDir disable/" /etc/httpd/conf/httpd.conf
        sed -i "s/#UserDir public_html/UserDir public_html/" /etc/httpd/conf/httpd.conf
        sed -i "370,381 s/#/ /" /etc/httpd/conf/httpd.conf
        echo -e "OK\n" | tee -a $logFile

}
#creates user home dir and sets the correct permissions
function creatDir {
        echo "creating the public_html dir for the users" | tee -a $logFile
        setsebool -P httpd_enable_homedirs true
        for userDir in $(ls /home); do
                if [! -d /home/$userDir/public_html ]; then
                        mkdir /home/$userDir/public_html
                        chmod 711 /home/$userDir
                        chmod 755 /home/$userDir/public_html
                        chown $userDir /home/$userDir/public_html
                        chgrp $userDir /home/$userDir/public_html
                fi
        done
        echo -e "OK\n" | tee -a $logFile
}
#starts the service
function startServices (){
        echo "Startign apache now" | tee -a $logFile
        /usr/local/apache/bin/apachectl start
        echo -e "OK\n" | tee -a $logFile
}
#main
apacheInstall $logFile
firewallConf $logFile
certCreate $logFile
apachConf $logFile
creatDir $logFile
startServices $logFile
echo "Finally Done" | tee -a $logFile
